# Generated by Django 5.0.1 on 2024-03-09 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DestinationModel",
            fields=[
                ("destination_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slogan", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog_images"),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegionModel",
            fields=[
                ("region_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog_images"),
                ),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_nav", models.BooleanField(default=False)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour.destinationmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TourDetailsModel",
            fields=[
                ("activity_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("depature", models.CharField(blank=True, max_length=100, null=True)),
                ("time", models.TimeField(null=True)),
                ("start_end", models.CharField(blank=True, max_length=200, null=True)),
                ("max_price", models.CharField(blank=True, max_length=200, null=True)),
                ("price", models.CharField(max_length=200)),
                ("transport", models.CharField(blank=True, max_length=200, null=True)),
                ("season", models.CharField(blank=True, max_length=200, null=True)),
                ("altitude", models.CharField(blank=True, max_length=200, null=True)),
                ("age", models.CharField(blank=True, max_length=200, null=True)),
                ("days", models.CharField(blank=True, max_length=200, null=True)),
                ("map", models.URLField(blank=True, db_index=True, unique=True)),
                ("map_overview", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog_images"),
                ),
                ("is_activity", models.BooleanField(default=False)),
                ("is_acttraction", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour.destinationmodel",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour.regionmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItinatyModel",
            fields=[
                ("itinary_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("day", models.IntegerField()),
                ("start_end", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField()),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour.tourdetailsmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GallaryModel",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog_images"),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tour.tourdetailsmodel",
                    ),
                ),
            ],
        ),
    ]
