# Generated by Django 5.0 on 2024-01-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('destinati_id', models.AutoField(primary_key=True, serialize=False)),
                ('priority_name', models.CharField(max_length=100)),
                ('destination_name', models.ImageField(upload_to=None)),
                ('slogan', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('destination_image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('discription', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('region_image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('discription', models.TextField(max_length=2000)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('actvity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100)),
                ('is_activity', models.BooleanField(default=False)),
                ('is_acttraction', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('activity_image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('discription', models.TextField(max_length=2000)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.region')),
            ],
        ),
    ]
