# Generated by Django 5.0 on 2024-04-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_destinationmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinatymodel',
            name='day',
            field=models.IntegerField(blank=True),
        ),
    ]
