# Generated by Django 5.0 on 2024-01-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_destinationmodel_remove_region_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionmodel',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='regionmodel',
            old_name='region_image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='is_nav',
            field=models.BooleanField(default=False),
        ),
    ]
