# Generated by Django 5.0 on 2024-03-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_includeexcludemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourIncludeExcludeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_included', models.BooleanField(default=True)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.includeexcludemodel')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourdetailsmodel')),
            ],
        ),
    ]
