# Generated by Django 5.0.6 on 2024-05-19 15:11

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_regionmodel_slug_tourdetailsmodel_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinatymodel',
            name='start_end',
        ),
        migrations.RemoveField(
            model_name='tourdetailsmodel',
            name='time',
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='tourdetailsmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='name', unique=True),
        ),
    ]
