# Generated by Django 5.0.1 on 2024-04-04 18:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0003_tourincludeexcludemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourdetailsmodel",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
