# Generated by Django 5.0 on 2024-05-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_itinatymodel_start_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetailsmodel',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], default='moderate', max_length=10),
        ),
        migrations.AlterField(
            model_name='tourdetailsmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='blog_images'),
        ),
    ]
