# Generated by Django 5.0 on 2024-04-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_tourincludeexcludemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourdetailsmodel',
            old_name='is_acttraction',
            new_name='is_attraction',
        ),
    ]
