# Generated by Django 5.0 on 2024-04-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_alter_itinatymodel_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinatymodel',
            name='day',
            field=models.CharField(max_length=2),
        ),
    ]
