# Generated by Django 5.0 on 2024-05-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tourdetailsmodel_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetailsmodel',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Difficult', 'Difficult')], default='Moderate', max_length=10),
        ),
    ]
