# Generated by Django 5.0 on 2024-01-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_tourdetailsmodel_delete_activitiesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetailsmodel',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
