# Generated by Django 5.0 on 2024-01-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_tourdetailsmodel_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItinatyModel',
            fields=[
                ('itinary_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('day', models.IntegerField(max_length=2)),
                ('start_end', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(max_length=2000)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourdetailsmodel')),
            ],
        ),
    ]
