# Generated by Django 5.0.1 on 2024-01-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0006_itinatymodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destinationmodel",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
