# Generated by Django 5.0 on 2024-06-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_alter_tourdetailsmodel_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetailsmodel',
            name='map',
            field=models.URLField(blank=True, db_index=True, max_length=2048, unique=True),
        ),
    ]
