# Generated by Django 5.0.1 on 2024-01-29 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tour", "0007_alter_destinationmodel_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="destinationmodel",
            old_name="destinati_id",
            new_name="destination_id",
        ),
    ]
