# Generated by Django 5.0 on 2024-07-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_tourdetailsmodel_itinary_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodel',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
