# Generated by Django 5.0 on 2024-07-21 05:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_regionmodel_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
