# Generated by Django 5.0 on 2024-02-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_rename_actvity_id_tourdetailsmodel_activity_id_and_more'),
        ('tour', '0010_alter_destinationmodel_name_alter_itinatymodel_day'),
    ]

    operations = [
    ]
