# Generated by Django 5.0 on 2024-07-21 18:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_alter_regionmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
