# Generated by Django 5.0 on 2024-07-22 03:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_alter_regionmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='faqmodels',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='itinatymodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tourdetailsmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='tourdetailsmodel',
            name='map_overview',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
