# Generated by Django 5.0 on 2024-07-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_specialmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdetailsmodel',
            name='star_rating',
            field=models.CharField(blank=True, default='79', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourdetailsmodel',
            name='total_reviews',
            field=models.CharField(blank=True, default='5', max_length=200, null=True),
        ),
    ]
