# Generated by Django 5.0 on 2024-07-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_tourdetailsmodel_star_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinatymodel',
            name='day',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='tourdetailsmodel',
            name='star_rating',
            field=models.CharField(blank=True, default='5', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tourdetailsmodel',
            name='total_reviews',
            field=models.CharField(blank=True, default='79', max_length=200, null=True),
        ),
    ]
