# Generated by Django 5.0 on 2024-07-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_alter_itinatymodel_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinatymodel',
            name='day',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='itinatymodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
