# Generated by Django 5.0 on 2024-09-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0017_tourdetailsmodel_price_1_tourdetailsmodel_price_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedTourModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourdetailsmodel')),
            ],
        ),
    ]
