# Generated by Django 5.0 on 2024-04-27 07:00

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='about_us',
            field=django_summernote.fields.SummernoteTextField(),
        ),
        migrations.AlterField(
            model_name='csrmodel',
            name='description',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
