# Generated by Django 5.0 on 2024-05-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discription', models.CharField(max_length=250)),
            ],
        ),
    ]
