# Generated by Django 5.0 on 2024-04-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='telephone',
            field=models.CharField(default='+977 14022020', max_length=15),
        ),
    ]
