# Generated by Django 4.2 on 2024-03-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGallaryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='blog_images')),
            ],
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='about_us',
            field=models.TextField(),
        ),
    ]
