# Generated by Django 5.0 on 2024-01-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='about_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='banner1_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='banner2_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='home_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='video_thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
    ]
