# Generated by Django 5.0 on 2024-03-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_maingallarymodel_alter_companyprofile_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
            ],
        ),
    ]
