# Generated by Django 5.0 on 2024-04-28 08:34

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blogsmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='why_us',
            field=django_summernote.fields.SummernoteTextField(default='about us'),
        ),
        migrations.AlterField(
            model_name='review',
            name='team_image',
            field=models.ImageField(null=True, upload_to='blog_images'),
        ),
    ]
