# Generated by Django 5.0 on 2024-01-24 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_companyprofile_about_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='about_sub_heading',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
