# Generated by Django 5.0 on 2024-07-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_seomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourteammodel',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='ourteammodel',
            name='instagram_link',
        ),
    ]
