# Generated by Django 5.0 on 2024-01-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_companyprofile_about_sub_heading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_image', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
