# Generated by Django 5.0 on 2024-04-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_companyprofile_why_us_alter_review_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteammodel',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
