# Generated by Django 5.0 on 2024-04-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_ourteammodel_team_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteammodel',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs_images/'),
        ),
    ]
