# Generated by Django 5.0 on 2024-01-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunfactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travellers', models.CharField(max_length=200)),
                ('places', models.CharField(max_length=200)),
                ('miles', models.CharField(max_length=200)),
                ('years', models.CharField(max_length=200)),
            ],
        ),
    ]
