# Generated by Django 5.0 on 2024-07-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_seomodel_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='home_image1',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='home_image2',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='home_image3',
            field=models.ImageField(blank=True, null=True, upload_to='company_images'),
        ),
    ]
