# Generated by Django 5.0 on 2024-07-22 03:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_companyprofile_home_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='about_us',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='csrmodel',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ourteammodel',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
