# Generated by Django 5.0 on 2024-01-28 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_funfactmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurTeam',
            new_name='OurTeamModel',
        ),
    ]
