# Generated by Django 5.0 on 2024-08-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blogsmodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldWideRepModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog_images')),
                ('flag', models.ImageField(upload_to='blog_images')),
            ],
        ),
    ]
