# Generated by Django 5.0 on 2024-02-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_blogsmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsmodel',
            old_name='team_image',
            new_name='image',
        ),
    ]
